### ISSUE TITLE
Debounce Input

### ISSUE THREAD

**Issue by Raggyman** [charliekassel/vuejs-autocomplete#45]
It would be really handy to have a "debounce" setting so that only after the selected time period the request is sent.  

Great work BTW.

**Comment by charliekassel** [comment]
It is already debounced for an xhr request, although the timing is hardcoded.
https://github.com/charliekassel/vuejs-autocomplete/blob/master/src/components/Autocomplete.vue#L226-L238

**Comment by rmedcalf** [comment]
I needed more control when to execute the search. Even if I could change debounce it still wouldn't be reliable due to the search implementation in the backend. I decided to execute search after the user presses the enter key

So I added a ref to the autocomplete component, gave the source an empty array, did the ajax call in my own code, and then populated the results property with my ajax results

```html
<autocomplete ref="searchBox" :source="[]" :showNoResults="myShowNoResults" @enter="runSearch" > </autocomplete>
```

```javascript 
async runSearch() {
  let searchBox = this.$refs.searchBox;
  if(searchBox.display) {
    let results = await this.$http.get('${url}?text=${searchBox.display}');
    searchBox.results = results.data;
    if(!searchBox.results) this.myShowNoResults = true;
  }
}
```
