### ISSUE TITLE
Delay the search

### ISSUE THREAD

**Issue by Matthewloughton** [charliekassel/vuejs-autocomplete#66]
Good day,

First of all, I love this component, you've done well and it was exactly what we were looking for.

I see someone has requested this already but I want to add.

The search is definitely delayed however all requests seems to continue even though the user is still typing.
Our search queries are pretty heavy and its creates a few unnecessary requests to the server.

I'm not sure if debounce does it already but I've personally implemented something like this before but what you can do is:

function yourKeyUpFunction(){
 clearTimeout(this.searchTimeout); //where searchTimeout is a var on the component

 this.searchTimeout = setTimeout(() => {
   //do the search
 }, 200);
}

This will ensure that the **last** request will be sent through 200ms after the user has stopped typing.

**Comment by rafadpedrosa** [comment]
The same is happening with me @Matthewloughton. 

Well, since i'm using this in one of my projects. I forked and improved the code to work with the debounce correctly.  Also added a delay parameter

@charliekassel May I create a pull request? 

Lines added + changed.  (https://github.com/rafadpedrosa/vuejs-autocomplete/tree/delay_prop)

```
...
    /**
     * A delay property. (optional)
     */
    delay: {
      type: [Number],
      required: false,
      default: 200
    },
...
    /**
     * Search wrapper method that emits an event for the real search with debounce
     */
    search () {
      this.$emit('search', this.delay)
    },
   /**
     * This method is called by the event inside mounted LCH for the debounce propose
     */
    searchEmitted () {
      this.selectedIndex = null
      switch (true) {
        case typeof this.source === 'string':
          // No resource search with no input
          if (!this.display || this.display.length < 1) {
            return
          }

          return this.resourceSearch(this.source + this.display)
        case typeof this.source === 'function':
          // No resource search with no input
          if (!this.display || this.display.length < 1) {
            return
          }
          return this.resourceSearch(this.source(this.display))
        case Array.isArray(this.source):
          return this.arrayLikeSearch()
        default:
          throw new TypeError()
      }
    },
...
    resourceSearch (url) { ... }, // debounce removed
...
  mounted () {
    this.$on('search', debounce(this.searchEmitted, this.delay)) // event added
...
```

**Comment by emad-sure** [comment]
@rafadpedrosa  hey whenever i try to install the package from you fork through your GitHub username / repo name 
it already install the package but empty !!! jus the Readme, package.json and License files only so how i can pull your changes to the package

**Comment by rafadpedrosa** [comment]
Hello @emad-sure!  How are you doing?

Sure, let me help you! First things first: You just want to use that? If so you will have to add it to your package.json as I did here:

```
{ 
 ... 
 "vuejs-auto-complete": "github:rafadpedrosa/vuejs-autocomplete#v0.9.1"
 ...
}
```

I did not add it into an npm package. Since it is a fork I'm not sure if I should be doing that and, that is why I ask the author if he wants me to push the implementation. 

I did not try to **build** then add it to a Vuejs app/instance. That's what you are trying to archive? If so, why? You can do by the package.json.

If you want to make your own changes, you can use the master or create any other branch, npm install then npm run dev. 

Open the **Demo.vue** and test it :)

I hope it helps you. Let me know if you need anything more
